[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mgit"
version = "0.1.0"
requires-python = ">=3.10"

[project.scripts]
mgit = "app.cli.cli:main"

[tool.setuptools.packages.find]
where = ["."]